# Generated by Django 2.0.4 on 2018-05-01 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkedinprofile',
            name='access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='linkedinprofile',
            name='expires_in',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
