# Generated by Django 2.0.4 on 2018-05-01 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bios', '0002_auto_20180501_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='temporal_state',
            field=models.TextField(blank=True, null=True),
        ),
    ]
