# Generated by Django 2.0.4 on 2018-05-01 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bios', '0003_candidate_temporal_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkedinprofile',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linkedin_profile', to='bios.Candidate'),
        ),
        migrations.AlterField(
            model_name='torreprofile',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='torre_profile', to='bios.Candidate'),
        ),
    ]
