# Generated by Django 2.0.4 on 2018-05-01 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bios', '0004_auto_20180501_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkedinprofile',
            name='candidate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='linkedin_profile', to='bios.Candidate'),
        ),
        migrations.AlterField(
            model_name='torreprofile',
            name='candidate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='torre_profile', to='bios.Candidate'),
        ),
    ]
